import { ModuleId, ModuleMetadata } from '@/types/simulation';

export const MODULE_REGISTRY: Record<ModuleId, ModuleMetadata> = {
  // --- MÓDULO A: FUERZAS INTERMOLECULARES ---
  'A1': {
    id: 'A1',
    unitCode: 'Unit 3.1',
    title: 'London Dispersion Forces',
    subtitle: 'Temporary shifts in electron density',
    category: 'IMF',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 30, attractionStrength: 0.15, volume: 100, pressure: 1, particleCount: 26 },
    description: 'London dispersion forces arise from instantaneous, temporary dipoles. They are the weakest intermolecular forces and increase with polarizability.',
    studentExercise: 'Move the attraction/polarizability slider and observe how particles move independently with weak temporary clustering.',
    programmerNotes: 'Monocolor particles, wide spacing, elastic collisions, weak clustering on high attraction.',
  },
  'A2': {
    id: 'A2',
    unitCode: 'Unit 3.1',
    title: 'Dipole-Dipole Forces',
    subtitle: 'Permanent partial charges and molecular orientation',
    category: 'IMF',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 30, attractionStrength: 0.45, volume: 100, pressure: 1, particleCount: 26 },
    description: 'Polar molecules have permanent partial charges. Opposite ends (+ and -) attract each other and induce rotational alignment.',
    studentExercise: 'Observe how the two-tone particles rotate so opposite charges align, staying closer together than in dispersion forces.',
    programmerNotes: 'Bicolor particles (half red / half blue) with angle theta and angular torque toward opposite poles.',
  },
  'A3': {
    id: 'A3',
    unitCode: 'Unit 3.1',
    title: 'Ion-Dipole Forces',
    subtitle: 'Aqueous solvation and charge hydration shell',
    category: 'IMF',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 25, attractionStrength: 0.75, volume: 100, pressure: 1, particleCount: 24 },
    description: 'Ion-dipole attractions occur between a full ionic charge and the partial charge of polar molecules, driving dissolution in polar solvents.',
    studentExercise: 'Observe how polar solvent molecules rotate their oppositely charged ends to surround and stabilize the central ion.',
    programmerNotes: 'One central large ion with surrounding polar dipoles orienting directly towards the ion.',
  },
  'A4': {
    id: 'A4',
    unitCode: 'Unit 3.1',
    title: 'Hydrogen Bonding',
    subtitle: 'Strong directional dipole interaction (H with N, O, F)',
    category: 'IMF',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 25, attractionStrength: 0.85, volume: 100, pressure: 1, particleCount: 30 },
    description: 'A special, strong case of dipole-dipole attraction occurring when hydrogen is bonded to highly electronegative N, O, or F.',
    studentExercise: 'Observe the tighter packing and directional dashed bonds that form between neighboring particles.',
    programmerNotes: 'High packing density, directional vectors and dashed connection lines between interacting pairs.',
  },
  'A6': {
    id: 'A6',
    unitCode: 'Unit 3.1',
    title: 'Ion-Ion Attractions',
    subtitle: 'Rigid electrostatic lattice',
    category: 'IMF',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 20, attractionStrength: 0.98, volume: 100, pressure: 1, particleCount: 36 },
    description: 'Full electrostatic forces between alternating cations and anions in a rigid lattice structure with high melting points.',
    studentExercise: 'Notice how particles stay locked in a rigid repeating grid with only tiny thermal vibrations.',
    programmerNotes: 'Rigid alternating grid with thermal vibration only.',
  },

  // --- MÓDULO B: ESTADOS DE LA MATERIA Y MEZCLAS ---
  'B1.1': {
    id: 'B1.1',
    unitCode: 'Unit 3.3',
    title: 'Liquid: Low Temperature',
    subtitle: 'Close contact with sliding mobility',
    category: 'STATES_OF_MATTER',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 20, attractionStrength: 0.6, volume: 100, pressure: 1, particleCount: 50 },
    description: 'Liquid particles remain close together while sliding past each other, having definite volume but fluid shape.',
    studentExercise: 'Move the temperature slider and observe how particles stay condensed at the bottom of the beaker.',
    programmerNotes: 'Particles condensed at bottom with slow sliding motion.',
  },
  'B1.2': {
    id: 'B1.2',
    unitCode: 'Unit 3.3',
    title: 'Liquid: Intermediate Motion',
    subtitle: 'Faster motion within condensed phase',
    category: 'STATES_OF_MATTER',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 50, attractionStrength: 0.6, volume: 100, pressure: 1, particleCount: 50 },
    description: 'Increasing temperature raises kinetic energy and collision rate while keeping the sample condensed.',
    studentExercise: 'Compare increased particle velocity to the low temperature state.',
    programmerNotes: 'Higher velocity within liquid layer.',
  },
  'B1.3': {
    id: 'B1.3',
    unitCode: 'Unit 3.3',
    title: 'Liquid: Approaching Vaporization',
    subtitle: 'Surface particles gaining escape velocity',
    category: 'STATES_OF_MATTER',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 85, attractionStrength: 0.6, volume: 100, pressure: 1, particleCount: 50 },
    description: 'At higher temperatures, energetic surface particles overcome IMFs and begin to evaporate into the space above.',
    studentExercise: 'Observe surface particles occasionally breaking free into the vapor space above the liquid.',
    programmerNotes: 'Allow energetic surface particles to leave the condensed boundary.',
  },
  'B2.1': {
    id: 'B2.1',
    unitCode: 'Unit 3.3',
    title: 'Gas: Low Temperature',
    subtitle: 'Large spacing with free motion',
    category: 'STATES_OF_MATTER',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 25, attractionStrength: 0, volume: 100, pressure: 0.5, particleCount: 25 },
    description: 'Gas particles fill the entire container with large empty space and elastic wall collisions.',
    studentExercise: 'Observe the large empty distance between gas particles throughout the closed vessel.',
    programmerNotes: 'Particles spread across whole container with slower speeds.',
  },
  'B2.2': {
    id: 'B2.2',
    unitCode: 'Unit 3.3',
    title: 'Gas: Moderate Temperature',
    subtitle: 'Higher collision frequency',
    category: 'STATES_OF_MATTER',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 55, attractionStrength: 0, volume: 100, pressure: 1.1, particleCount: 25 },
    description: 'Heating a gas increases collision frequency and wall impact momentum.',
    studentExercise: 'Notice how particle collisions become more frequent as temperature increases.',
    programmerNotes: 'Increased velocity and collision count.',
  },
  'B2.3': {
    id: 'B2.3',
    unitCode: 'Unit 3.3',
    title: 'Gas: High Temperature',
    subtitle: 'Maximum average kinetic energy',
    category: 'STATES_OF_MATTER',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 90, attractionStrength: 0, volume: 100, pressure: 1.8, particleCount: 25 },
    description: 'Highest collision intensity and speed. Average kinetic energy is proportional to Kelvin temperature.',
    studentExercise: 'Observe the most rapid motion and highest wall collision force in the gas set.',
    programmerNotes: 'Fastest straight line motion and elastic collisions.',
  },
  'B3.1': {
    id: 'B3.1',
    unitCode: 'Unit 3.3',
    title: 'Crystalline Solid (Ordered)',
    subtitle: 'Fixed lattice with small vibrations',
    category: 'STATES_OF_MATTER',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 15, attractionStrength: 1, volume: 100, pressure: 1, particleCount: 40 },
    description: 'Crystalline solids have long-range 3D periodic order with particles vibrating about fixed lattice points.',
    studentExercise: 'Observe the regular repeating pattern of particles in the solid.',
    programmerNotes: 'Tightly packed regular grid with small vibration.',
  },
  'B3.2': {
    id: 'B3.2',
    unitCode: 'Unit 3.3',
    title: 'Crystalline Solid (Warming)',
    subtitle: 'Larger vibration amplitude',
    category: 'STATES_OF_MATTER',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 50, attractionStrength: 1, volume: 100, pressure: 1, particleCount: 40 },
    description: 'Warming increases vibration amplitude while preserving the crystalline lattice intact.',
    studentExercise: 'Raise temperature and observe stronger vibration without lattice disruption.',
    programmerNotes: 'Increase vibration amplitude while maintaining fixed grid coordinates.',
  },
  'B3.3': {
    id: 'B3.3',
    unitCode: 'Unit 3.3',
    title: 'Crystalline Solid (Near Melting)',
    subtitle: 'Maximum vibration before phase change',
    category: 'STATES_OF_MATTER',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 85, attractionStrength: 1, volume: 100, pressure: 1, particleCount: 40 },
    description: 'Just prior to the sharp melting point, the crystal structure holds despite intense local vibration.',
    studentExercise: 'Observe the solid right before melting: high kinetic agitation with intact structure.',
    programmerNotes: 'Maximum vibration without breaking lattice sites.',
  },
  'B4.1': {
    id: 'B4.1',
    unitCode: 'Unit 3.3',
    title: 'Amorphous Solid (Disordered)',
    subtitle: 'Closely packed without long-range order',
    category: 'STATES_OF_MATTER',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 15, attractionStrength: 0.9, volume: 100, pressure: 1, particleCount: 45 },
    description: 'Amorphous solids (like polymers/glass) lack long-range repeating symmetry.',
    studentExercise: 'Compare the disordered particle arrangement to the crystalline solid.',
    programmerNotes: 'Disordered dense arrangement with local vibration.',
  },
  'B4.2': {
    id: 'B4.2',
    unitCode: 'Unit 3.3',
    title: 'Amorphous Solid (Softening)',
    subtitle: 'Gradual softening over temperature range',
    category: 'STATES_OF_MATTER',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 50, attractionStrength: 0.8, volume: 100, pressure: 1, particleCount: 45 },
    description: 'Amorphous solids do not have a sharp melting point; they soften gradually as viscosity decreases.',
    studentExercise: 'Notice how the disordered material begins to yield without an abrupt phase boundary.',
    programmerNotes: 'Increase disorder and slight deformation with temperature.',
  },
  'B4.3': {
    id: 'B4.3',
    unitCode: 'Unit 3.3',
    title: 'Amorphous Solid (Viscous Flow)',
    subtitle: 'Polymer chain mobility',
    category: 'STATES_OF_MATTER',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 85, attractionStrength: 0.7, volume: 100, pressure: 1, particleCount: 45 },
    description: 'At elevated temperatures, amorphous solids behave like highly viscous liquids.',
    studentExercise: 'Observe the gradual flow while remaining disordered.',
    programmerNotes: 'Viscous, disordered deformation under high thermal energy.',
  },
  'B5.1': {
    id: 'B5.1',
    unitCode: 'Unit 3.10',
    title: 'Insoluble Mixture (Phase Separation)',
    subtitle: 'Unfavorable unlike attractions',
    category: 'STATES_OF_MATTER',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 25, attractionStrength: 0.5, volume: 100, pressure: 1, particleCount: 48 },
    description: 'Immischible substances separate into distinct phases because like-like attractions are much stronger than solute-solvent interactions.',
    studentExercise: 'Observe two distinct layers formed by the two different particle types.',
    programmerNotes: 'Two distinct particle types with clear boundary layer.',
  },
  'B5.2': {
    id: 'B5.2',
    unitCode: 'Unit 3.10',
    title: 'Insoluble Mixture (Temperature Effect)',
    subtitle: 'Increased motion without mixing',
    category: 'STATES_OF_MATTER',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 60, attractionStrength: 0.5, volume: 100, pressure: 1, particleCount: 48 },
    description: 'Higher temperature increases collision frequency, but phase separation persists due to unfavorable energetics.',
    studentExercise: 'Notice that heating increases motion but does not create a uniform solution.',
    programmerNotes: 'Increased velocity with phase boundary preserved.',
  },
  'B5.3': {
    id: 'B5.3',
    unitCode: 'Unit 3.10',
    title: 'Insoluble Mixture (Persistent Separation)',
    subtitle: 'Brief boundary crossings only',
    category: 'STATES_OF_MATTER',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 90, attractionStrength: 0.5, volume: 100, pressure: 1, particleCount: 48 },
    description: 'Even at high kinetic energy, particles crossing the boundary are rejected back to their like phase.',
    studentExercise: 'Observe particles crossing the boundary only to be pushed back into their respective layer.',
    programmerNotes: 'Repulsive barrier prevents homogenous mixing.',
  },
  'B6.1': {
    id: 'B6.1',
    unitCode: 'Unit 3.10',
    title: 'Soluble Mixture (Dispersion Begins)',
    subtitle: 'Favorable solute-solvent attraction',
    category: 'STATES_OF_MATTER',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 25, attractionStrength: 0.6, volume: 100, pressure: 1, particleCount: 48 },
    description: 'Favorable intermolecular attractions between unlike particles allow solute to dissolve into solvent.',
    studentExercise: 'Observe solute particles starting to disperse through the solvent gradient.',
    programmerNotes: 'Solute particles dispersing into solvent medium.',
  },
  'B6.2': {
    id: 'B6.2',
    unitCode: 'Unit 3.10',
    title: 'Soluble Mixture (Faster Dissolution)',
    subtitle: 'Thermal acceleration of mixing',
    category: 'STATES_OF_MATTER',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 55, attractionStrength: 0.6, volume: 100, pressure: 1, particleCount: 48 },
    description: 'Higher temperatures speed up the rate of dissolving as kinetic diffusion increases.',
    studentExercise: 'Raise temperature and watch the mixture become homogeneous more quickly.',
    programmerNotes: 'Uniform distribution spreading rapidly.',
  },
  'B6.3': {
    id: 'B6.3',
    unitCode: 'Unit 3.10',
    title: 'Soluble Mixture (Homogeneous Solution)',
    subtitle: 'Completely uniform single phase',
    category: 'STATES_OF_MATTER',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 85, attractionStrength: 0.6, volume: 100, pressure: 1, particleCount: 48 },
    description: 'A completely homogeneous single phase maintained at thermal equilibrium.',
    studentExercise: 'Observe the completely uniform distribution of both particle types.',
    programmerNotes: 'Fully homogeneous particle distribution across entire liquid volume.',
  },

  // --- MÓDULO C: SÓLIDOS 3D (R3F) ---
  'C1': {
    id: 'C1',
    unitCode: 'Unit 3.2',
    title: 'Ionic Solid Lattice',
    subtitle: 'Alternating positive & negative ions',
    category: 'SOLIDS_3D',
    renderMode: '3D_R3F',
    defaultParams: { temperature: 20, attractionStrength: 0.95, volume: 100, pressure: 1, particleCount: 64 },
    description: 'An ionic solid made of alternating Na+ and Cl- ions in a rigid crystal lattice. Brittleness occurs when shifted planes align like charges.',
    studentExercise: 'Rotate the 3D crystal lattice and observe the alternating cation-anion arrangement.',
    programmerNotes: 'Alternating 3D cubic lattice of small red cations and large blue anions.',
  },
  'C2': {
    id: 'C2',
    unitCode: 'Unit 3.2',
    title: 'Metallic Solid & Electron Sea',
    subtitle: 'Cation cores in mobile electron cloud',
    category: 'SOLIDS_3D',
    renderMode: '3D_R3F',
    defaultParams: { temperature: 25, attractionStrength: 0.9, volume: 100, pressure: 1, particleCount: 64, magnetEngaged: false },
    description: 'Fixed metallic cation cores surrounded by delocalized mobile valence electrons explaining electrical conductivity and malleability.',
    studentExercise: 'Toggle the magnet control to see delocalized electrons migrate toward the magnetic field while cations stay fixed.',
    programmerNotes: 'Fixed cation spheres with tiny fast orbiting/mobile electron particles and a magnet toggle response.',
  },
  'C3': {
    id: 'C3',
    unitCode: 'Unit 3.2',
    title: 'Molecular Solid Lattice',
    subtitle: 'Discrete molecules held by IMFs',
    category: 'SOLIDS_3D',
    renderMode: '3D_R3F',
    defaultParams: { temperature: 20, attractionStrength: 0.5, volume: 100, pressure: 1, particleCount: 48 },
    description: 'Discrete molecular units packed in a crystal lattice, held by intermolecular forces rather than covalent networks.',
    studentExercise: 'Notice how discrete molecular clusters vibrate as individual units.',
    programmerNotes: 'Render clusters of bonded atoms acting as individual molecular units packed in 3D.',
  },
  'C4': {
    id: 'C4',
    unitCode: 'Unit 3.2',
    title: 'Covalent Network Solid (SiO2 / Diamond)',
    subtitle: 'Continuous macromolecular bonding',
    category: 'SOLIDS_3D',
    renderMode: '3D_R3F',
    defaultParams: { temperature: 20, attractionStrength: 1, volume: 100, pressure: 1, particleCount: 64 },
    description: 'Atoms connected by continuous covalent bonds throughout the entire structure, resulting in exceptional hardness and high melting points.',
    studentExercise: 'Compare this continuous bonded network with the discrete molecular solid.',
    programmerNotes: 'Connected 3D lattice with visible covalent bond cylinders between all adjacent atoms.',
  },

  // --- MÓDULO D: LEYES DE GASES (PV = nRT) ---
  'D1': {
    id: 'D1',
    unitCode: 'Unit 3.5',
    title: 'Ideal Gas: Changes in P & V (Boyle)',
    subtitle: 'Inverse P-V relationship at constant n and T',
    category: 'GAS_LAWS',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 50, attractionStrength: 0, volume: 80, pressure: 1.2, particleCount: 35 },
    description: 'At constant moles and temperature, pressure is inversely proportional to volume (P = nRT / V).',
    studentExercise: 'Drag the volume slider and observe how pressure changes inversely.',
    programmerNotes: 'Piston chamber with particle collisions determining pressure gauge reading.',
  },
  'D2': {
    id: 'D2',
    unitCode: 'Unit 3.5',
    title: 'Ideal Gas: Changes in P & T (Gay-Lussac)',
    subtitle: 'Direct P-T relationship at constant V and n',
    category: 'GAS_LAWS',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 50, attractionStrength: 0, volume: 60, pressure: 1.0, particleCount: 35 },
    description: 'At constant volume and moles, pressure is directly proportional to absolute temperature in Kelvin.',
    studentExercise: 'Increase temperature and observe the proportional rise in pressure gauge reading.',
    programmerNotes: 'Fixed volume piston. Higher temperature increases particle speed and collision impulse.',
  },
  'D3': {
    id: 'D3',
    unitCode: 'Unit 3.5',
    title: 'Ideal Gas: Changes in n & T',
    subtitle: 'Inverse n-T tradeoff at constant P and V',
    category: 'GAS_LAWS',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 50, attractionStrength: 0, volume: 60, pressure: 1.0, particleCount: 35 },
    description: 'With pressure and volume fixed, fewer particles must move faster (higher T) to sustain the same pressure.',
    studentExercise: 'Adjust particle count (moles) and observe how temperature compensates.',
    programmerNotes: 'Tradeoff between particle count and speed to hold pressure constant.',
  },
  'D4': {
    id: 'D4',
    unitCode: 'Unit 3.5',
    title: 'Ideal Gas: Changes in n & P (Avogadro)',
    subtitle: 'Direct n-P relationship at constant V and T',
    category: 'GAS_LAWS',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 50, attractionStrength: 0, volume: 60, pressure: 1.0, particleCount: 30 },
    description: 'At constant volume and temperature, adding more gas moles directly increases pressure via more wall collisions.',
    studentExercise: 'Add particles to the container and observe the direct increase in pressure.',
    programmerNotes: 'Vary particle count while keeping container dimensions fixed.',
  },
  'D5': {
    id: 'D5',
    unitCode: 'Unit 3.5',
    title: 'Ideal Gas: Changes in n & V (Avogadro Law)',
    subtitle: 'Direct n-V relationship at constant P and T',
    category: 'GAS_LAWS',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 50, attractionStrength: 0, volume: 50, pressure: 1.0, particleCount: 30 },
    description: 'At constant pressure and temperature, volume is directly proportional to moles of gas.',
    studentExercise: 'Change the number of moles and observe how the piston moves to adjust volume.',
    programmerNotes: 'Piston height expands or contracts proportionally with particle count.',
  },
  'D6': {
    id: 'D6',
    unitCode: 'Unit 3.5',
    title: 'Ideal Gas: Changes in T & V (Charles)',
    subtitle: 'Direct T-V relationship at constant P and n',
    category: 'GAS_LAWS',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 40, attractionStrength: 0, volume: 50, pressure: 1.0, particleCount: 30 },
    description: 'At constant pressure, gas volume is directly proportional to temperature in Kelvin.',
    studentExercise: 'Heat or cool the gas and watch the piston expand or contract to maintain constant pressure.',
    programmerNotes: 'Piston moves up with temperature increases to maintain constant pressure.',
  },

  // --- MÓDULO E & F: KMT Y MAXWELL-BOLTZMANN ---
  'E1': {
    id: 'E1',
    unitCode: 'Unit 3.4',
    title: 'KMT Simulation (Kinetic Molecular Theory)',
    subtitle: 'Elastic collisions and random straight-line motion',
    category: 'KMT_MAXWELL',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 45, attractionStrength: 0, volume: 100, pressure: 1.0, particleCount: 50 },
    description: 'Gas particles are in continuous, random straight-line motion, undergoing perfectly elastic collisions without intermolecular attractions.',
    studentExercise: 'Observe particles moving in straight lines between collisions and see how temperature scales average speed.',
    programmerNotes: 'Vectorial 2D elastic collisions between particles and container walls.',
  },
  'F1': {
    id: 'F1',
    unitCode: 'Unit 3.6',
    title: 'Maxwell-Boltzmann: High-Speed Tail',
    subtitle: 'Highlighting energetic particles on the curve',
    category: 'KMT_MAXWELL',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 50, attractionStrength: 0, volume: 100, pressure: 1.0, particleCount: 60 },
    description: 'Gas particles exhibit a distribution of speeds. Hovering over the high-speed region highlights particles moving faster than average.',
    studentExercise: 'Hover over the gray tail of the Maxwell-Boltzmann curve to highlight high-velocity particles in the chamber.',
    programmerNotes: 'Maxwell-Boltzmann distribution curve linked to real-time particle speed highlights.',
  },
  'F2': {
    id: 'F2',
    unitCode: 'Unit 3.6',
    title: 'Maxwell-Boltzmann: Peak / Average Speed',
    subtitle: 'Most probable molecular speed region',
    category: 'KMT_MAXWELL',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 50, attractionStrength: 0, volume: 100, pressure: 1.0, particleCount: 60 },
    description: 'The peak of the curve represents the most probable speed (v_mp), matching the largest fraction of particles.',
    studentExercise: 'Hover over the central pink band of the curve to see the large group of average-speed particles highlighted.',
    programmerNotes: 'Center band hover highlights particles with velocities near the distribution peak.',
  },
  'F3': {
    id: 'F3',
    unitCode: 'Unit 3.6',
    title: 'Maxwell-Boltzmann: Low-Speed Tail',
    subtitle: 'Particles with lower kinetic energy',
    category: 'KMT_MAXWELL',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 50, attractionStrength: 0, volume: 100, pressure: 1.0, particleCount: 60 },
    description: 'A fraction of particles move slower than average at any given temperature.',
    studentExercise: 'Hover over the blue low-speed band to highlight the slower-moving particles.',
    programmerNotes: 'Low-speed band hover highlights slow particles.',
  },
  'F4': {
    id: 'F4',
    unitCode: 'Unit 3.6',
    title: 'Maxwell-Boltzmann: Low Temperature Shift',
    subtitle: 'Taller, narrower distribution curve',
    category: 'KMT_MAXWELL',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 20, attractionStrength: 0, volume: 100, pressure: 1.0, particleCount: 60 },
    description: 'At lower temperature, average speed decreases and the curve becomes taller and narrower.',
    studentExercise: 'Notice how the curve concentrates at lower speeds with higher peak height.',
    programmerNotes: 'Curve morphs to taller, narrower shape at lower T.',
  },
  'F5': {
    id: 'F5',
    unitCode: 'Unit 3.6',
    title: 'Maxwell-Boltzmann: High Temperature Shift',
    subtitle: 'Broader, flatter distribution curve',
    category: 'KMT_MAXWELL',
    renderMode: '2D_CANVAS',
    defaultParams: { temperature: 85, attractionStrength: 0, volume: 100, pressure: 1.0, particleCount: 60 },
    description: 'At higher temperature, the distribution broadens and flattens as more particles attain higher velocities.',
    studentExercise: 'Observe the wider, flatter curve showing a broader spread of high particle velocities.',
    programmerNotes: 'Curve flattens and extends toward higher velocity on high T.',
  },
};
